export { default as exhibitActivationNoise } from './audio_files/exhibit_activation_noise.mp3';
export { default as musicIdle } from './audio_files/music_idle.wav';
export { default as musicBackground } from './audio_files/music_background.wav';
export { default as levelDefeat } from './audio_files/level_defeat.mp3';
export { default as paddleHit } from './audio_files/paddle_hit.mp3';
export { default as pointLose } from './audio_files/point_lose.mp3';
export { default as pointScore } from './audio_files/point_score.mp3';
export { default as wallHitLeft } from './audio_files/wall_hit_left.wav';
export { default as wallHitRight } from './audio_files/wall_hit_right.wav';